apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
  labels:
    test: test
    test2: test
    test3: testagain
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        test: test
        app: my-app
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8096
        resources:
          requests:
            memory: "1Gi"
            cpu: "0.5"
          limits:
            memory: "1Gi"
            cpu: "0.5"