apiVersion: v1
kind: Secret
metadata:
  name: ks-secret-25206
stringData:
  foo: bar
---
apiVersion: security.databricks.crossplane.io/v1alpha1
kind: Secret
metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
  name: sc-25206
  labels:
    test: test
spec:
  forProvider:
    key: sc-25206
    scope: personal
    stringValueSecretRef:
      key: foo
      name: ks-secret-25206
      namespace: data-mlops-dev-25206