apiVersion: v1
kind: Secret
metadata:
  name: my-secret
  annotations:
    argocd.argoproj.io/sync-wave: "1"
stringData:
  key: value
  please: break
  ok: just try again
  again: again
  itworked: trying another case
  onemore: shot
  new: new
  newnew: item`
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-test
  labels:
    test: test
    test2: label2
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-test
  template:
    metadata:
      labels:
        app: my-test
    spec:
      containers:
        error:
          fail: onpurpose
      - name: nginx
        image: nginx:latest
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config
  annotations:
    argocd.argoproj.io/sync-wave: "3"
data:
  key: value
  key2: value2
  infinite: loopplz
  another: causeimessedup
  lets: see
  new: new
  add: again
  try: again