---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: my-sealed-secret
  metadata:
  annotations:
    argocd.argoproj.io/sync-options: Force=true,Replace=true
spec:
  encryptedData:
    password: AgB38yyp8iowfDW+cqSaWPCD2ygwt5ct82rNbHe78lREWqQUjj0RNdP3KTIayYIpn5AkzRZopC704fS7BqNct4hF7U/bJGa/7dFzaP193N88ykiHebVhopiiV8dXeKnJRwpvfulsO3OT3d/LYRStRHRf5CycrXVfTxGfaSPIOSkHXFRfluWHliyX2+dvdcXWRuhk+Jbq6r39wPLgUostlRdAp6ePa16SFxJ+R4pPiCYjxIMIroEIqH9K5AU8Y9Tn8e+1oDaNJft4m3epDN/MZ0WAFaCnE0fjrQWpipW15W8ERMGcnXZuM/QcajHnCYEyXRBbrOi6HCCs1uZa7lAE0dtSJcY9I+wTpS1HfE/7Q7HC6ydGGXO+PZTdJ7cBG7WpsEEliCXgbsPidHz10gn4HFWWeLXcUKxBsRH6dSp/dHykoGFvFyrafsCOHKJ75cLZ8q4l/cXEYMM3KgS8OicLL4M9KWlDpwVqdmjeGmeN/NEFp7nfQmAfuI26rlx8ewIVdz5FA0XQE4l5Oxt3++PTv55Gvuooeb75ZR9OpWX2xKHFKuqV/yXgALvc1LRiEEW9sK577OUPM+vL6a721KXK1f6pX72T7hNu6l4qoDLQYOPPPu1glP4d2ONErF3PoQNSQMt+Yz8sr9mOoh7c9ZQyJ+Yuh7P58KLj+jv/GiQ2J02w0bnsznTqsRyHGhjodzeX0oAonwYwmX+2wA==
    username: AgBFTLBlydiGBved9E83ml2nogC1xIMShYNnXFPUuqdqnS54XfyC3OLaiJEEbF68Z/ugMIxceWtdTiKS4Z/1E70OFWo81pEvpiZupEPAD2XWOau3gapmhZIsGkPAy4TObfCfI3sjdYNJYzA+GCmETDhRJ5jDBWaxQFWrD4hb8px6TO6SM2pUir5RtA2iHPp2VHuTC5wnncJvB8fHBoOqsN+UhMT1gmn1uwTuEuyXmCt93tqzBIkufELao7U9aJAkx8D4NiYLXBuQeqmNPPoxcr5rhaTGufCApaEqKCkIAWSLEwCsonb+PHGBC8B7bvqhT0E6tarJf/HVsFseGeRNsg0nFc7dL+sAYO4bOqwrk/bIssBA51K63NaoI/P10UYNdk+KDpL32YV3UPEDY6g/zdF+INR1HSBJsKdDTSWiFdENfAxsIU2OHoBa/PXxqY5tnWrfVcC8SRrrl9WXy/igoeKLMnmoojcN3uCbCyLMVGsochmXkytvlP/j2L67nTUDGNmAL//SvBvP8PH0E9jvlgu1VMsq+KMOmUsiKRLmYHDMJAluk8esqV+Zv9H4FEBch/yQ2ZgwTLJkomSqQl0HRcfoLX0h0Vy4j4r9qxhWC6qqw/6cPpTiNQXFYJa3wXOMsi0rjiHzSzJDkKDSvJvQGk4OldUJFX1PeVawsq6+9t0U/68EGKe0sTVJRSXOapCp7IjWIAxAbvPIug==
  template:
    metadata:
      name: my-sealed-secret
      labels:
        test: test
