apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: data-mlops-dev-25206
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: data-mlops-dev
  source:
    repoURL: https://github.com/cjcocokrisp/argo-workspace
    targetRevision: HEAD
    path: issues/25206/user-resources
  destination:
    server: https://kubernetes.default.svc
    namespace: data-mlops-dev-25206
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
    automated:
      selfHeal: true