apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appaofapps
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: https://github.com/cjcocokrisp/argo-workspace
      path: issues/21869/apps
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true