apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: health-check-on-deletion
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cjcocokrisp/argo-workspace
    targetRevision: HEAD
    path: issues/25323/resources
  destination:
    name: in-cluster
    namespace: test
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true