apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: health-check-on-deletion-second
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/cjcocokrisp/argo-workspace
    targetRevision: HEAD
    path: issues/25323/resources2
  destination:
    name: in-cluster
    namespace: test2
  syncPolicy:
    syncOptions:
      - CreateNamespace=true