---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: sealed-secret-test
  namespace: default
spec:
  encryptedData:
    password: AgCZULpk27Tcxf6T9iAYTr4/hXWlFtjK+b/t7vraQqzxCVXGVn/cpvf1YLGRbe+q/EZYhRqxJbA/rCIASXZ18/fW8L0Kj5hp7RgNKvIDAzGZHlpm3/Up61ilkVi8xWQ0B25Watl7qxM9knBpZD7NAXQKjGTYcuOJf9BvQGBvHHlFefOH60rfZpnfCuuKvBR/fGMKGS2XS7OgIAZTE58p2jK3xqk1PNa9NoDkn5HbCgpkezQzYDYGA0SC/NCHUIIavZ7FKZvoTJxkYLT86HaVx5AVgz/WopFBBcaLiInhZUH/gy0FmMUMqGT7etFwGRIUKD63kXcHaEGwdS7tdt8d5h4qQAjpNxSGXYcC8O+Dd2slCI4jBZ2fOz3uhn00G08NSn/Q2DKArXFGXbL9j0KlB6q/NKFzig4o1z21X1+jDbR0VMkdhFPUkPuTeMPDRK3tGLlPdzr7Bbpy6t/MO4AjmPXojAqdUXRor6JgcbpHnh9LPPW6w6xrQvv6Bn2qNvP2eCSFy2xROz94BAFAjY2sT5qUjTRqbkClk5uyZDwxwxFepyHMQ3g+kyXBJirlY5vLv3BZ9Yvq35NBK0OaiWZNfb/kHq7ZY4J3HpeBoyulxUXWNQx0ZR5zMKoGCOpfeOMbMYil7SKODJ1+by7WEI28X7MZ8YFCCU9OZ2eO9/q+MepMEWHgwOxk/kKWGuZ7byHDjRgWsC92UeIhoQ==
    username: AgCFl4Q6Cn3ptKbnSvLivi7ATHlIdRwj6iqZ5WDMjzcyxHmlD7SSUEUQogrVIhfMFzzF2mBU9SiHZh0agtapmtwQJ/9AHKY8qYaV/cmhFeZdMuSOxl2t1iSPSmprwYXuE/wyaQoKUBHSlbzGEdq8ORXoQAsvIoq9G3a3x344TUA4Y//56u3dWMwGiy2NEEIJVhjjf5wCPbBlEVicIeiTi4vL3IpW9IQWPCCJAFMKBs7h7sd94DuOyQTXGr2+t0b9fxenaFG/zW5m7/45Vk+MAyRmBCtjqDarfnOateYI+HzsvieVd9ozLomPmU4Ii3V3VW8cc2+my537o4PRinXbGrUHMS950TTzwGpqUOjW9Kz2ngSyEwqRa1M840Hs7SXG1nGH3guzRSQjrNq/W3a3u9fdED5yOEcGtPFdR/owAKu4btic7Fv8s3XvOEk+NWW0kXBt8t/wwjC+ccfhuc4lgt7n7mbpjdtb9QFJj9JBf1MFAcYMyfGzmymvhoqGxqLCkOy3jGTU6sVU7LaBKTz7KEd10kgzJW3mGFV0ERJVhFXJ8HIxVBYYt37QyhQP3SmE/vj9FlMpL0pECI8Qh8C0tXbEghLwhWudLqhGgfGMZxMHucxEEXHXeA8C/IgsxoRwWpLwVjq12M8uXR7o1r3sJPey50OYNBg6oehhlZO/ksAO8TGDcikoEJn6PYN888b6z7qvpDMbk62BMg==
  template:
    metadata:
      name: sealed-secret-test
      namespace: default
