apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-app
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  sources:
    - repoURL: https://github.com/cjcocokrisp/argo-workspace.git
      path: promotions/resources