apiVersion: promoter.argoproj.io/v1alpha1
kind: GitRepository
metadata:
  name: argo-workspace-git-repo
spec:
  github:
    name: argo-workspace
    owner: cjcocokrisp
  scmProviderRef:
    name: github-scm-provider