apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
spec: 
  destination:
    name: in-cluster
    namespace: argocd
  source:
    path: issues/25855/apps
    repoURL: https://github.com/cjcocokrisp/argo-workspace
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - RespectIgnoreDifferences=true
  ignoreDifferences:
  - group: argoproj.io
    kind: Applications
    jsonPointers:
    - .spec.sources[] | select(.path == "issues/25855/chart") | .helm.valuesObject.replicas